### PR TITLE
TST: Fix subproc wait test

### PR DESCRIPTION
**Pull request by pllim**
Like #50 but for Jenkins CI.

### CODE REVIEW

**Comment by cdsontag** [comment]
This is what frightens me a bit.  Before you fixed it, the test did nothing, and it was known to do nothing (from the comment), and yet it was left that way.

**Comment by pllim** [comment]
There are currently only a few of such tests and they are all being tracked at #48. If you know how to fix up the rest, please do! :wink: 

(For all I know, it might not have been working properly too in pandokia, but it is just more visible now. This is unconfirmed though.)

**Comment by cdsontag** [comment]
Love to help out with more (I would!) but I've already spent way too much time on this.  Hey - have you guys abandoned pypi?  If not, we need to update what is out on pypi.

>  For all I know, it might not have been working properly too in pandokia, but it is just more visible now. This is unconfirmed though.

Nahh - it's been working there for years.  I posted in the other PR about just now finding when the test code recently got changed from using `==` to using `is`.

**Comment by pllim** [comment]
>  If not, we need to update what is out on pypi.

What do you mean? PyPI seems to be pointing to the same GitHub release (2.1.14).

**Comment by cdsontag** [comment]
I mean basically we should get the latest code into pypi (which I guess means make a release).  It's been quite a while.

**Comment by pllim** [comment]
I'll open an issue with your request, but maybe we should wait for some patches from @jehturner  first. Also, I don't have access to this package's PyPI, so it would have to be Joe or Matt when the time comes.

**Pull request merged**
