### PR TITLE
fix to subproc_tests.test() to not use "is" so casually

### PR DESCRIPTION
**Pull request by cdsontag**
This test is failing bc Subprocess.wait() returns an int, but we are checking for True (via `is`).  Not really sure how this was ever passing before, unless perhaps Py27 was casting that for us without our knowledge.

I have confirmed manually that the new code does The Right Thing here.  It should only throw the assert if `wait()` returns 0.

### CODE REVIEW

**Comment by cdsontag** [comment]
@pllim can this be merged as well?

**Comment by pllim** [comment]
Sure. Thanks!

**Comment by pllim** [comment]
Oh wait... Nitpick: Any chance you can squash it to get rid of the merge commit?

**Comment by pllim** [comment]
Oh, nevermind, there is a squash button here. Hahaha. Ignore my last comment.

**Comment by cdsontag** [comment]
>  Not really sure how this was ever passing before, unless perhaps Py27 was casting that for us without our knowledge.

Looking back in the code before some changes were made, I see that it used to use `==` instead of `is`.  So that's why it used to work.

BTW, that also shows that the test was changed but the changer never ran it to see if it worked.

**Comment by pllim** [comment]
`== True` is not recommended (related discussion at https://stackoverflow.com/questions/27276610/boolean-identity-true-vs-is-true), that was why it was changed to `is True` (`flake8` checker was also complaining about it). Any changes to the intention of the test was, well, unintentional. I apologize.

**Comment by cdsontag** [comment]
No worries!  As you know, since `== True`, is definitely not the same as `is True`, we should be careful about just changing things that way.

**Pull request merged**
